### ISSUE TITLE
Function score add should return current score 

### ISSUE THREAD

**Issue by mitjaresek** [tadej/hinko#2]
Function score add should return current score 
Example:
@hinko score add cobras:hawks 1:2  // should return

COBRAS are currently ahead of HAWKS: 18:6.

Here are the latest match results:
`2:1 on Tue, 19 Feb 2019 16:07:55 CET`
`2:0 on Mon, 18 Feb 2019 16:07:17 CET`
`2:0 on Thu, 07 Feb 2019 14:12:18 CET`
`2:0 on Wed, 06 Feb 2019 15:11:29 CET`

**Comment by tadej** [comment]
Good idea, thanks!
